#!/usr/bin/env bash
# Function to display information about domains & subdomain

print_dns () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    print_dns "$2.$1" "$2"
else
    print_dns "www.$1" "www"
    print_dns "lb-01.$1" "lb-01"
    print_dns "web-01.$1" "web-01"
    print_dns "web-02.$1" "web-02"
fi
