#!/usr/bin/env bash
# Transfer Files

if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# using variables
path_to_file="$1"
ip="$2"
username="$3"
path_to_ssh_key="$4"

# Transfer FILES
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$1":~
