#!/usr/bin/env bash
# prints "Best School" 10 times using whileloop then for the ninth iteration it prints hi

idx=1

while [ "$idx" -lt 11 ]; do
  echo "Best School"
  
  # if statement to print Hi when idx is 9
  if [ "$idx" -eq 9 ]; then
    echo "Hi"
  fi

  ((idx++))
done
